# fly.toml app configuration file generated for makkara on 2024-05-07T14:51:51+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'makkara'
primary_region = 'arn'
swap_size_mb = 1024

[build]

[env]
  PORT = '5000'

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = ''
  internal_port = 5000

  [[services.ports]]
    port = 80
    handlers = ['http']

[[vm]]
  size = 'shared-cpu-1x'
